In [1]:
import tensorflow as tf

# Manipulating tensors in tensorflow

## Basic operations ( pointwise )

In [2]:
A = tf.constant([[1, 2], [3, 4]])
A + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]])>

In [4]:
A # original tensor is unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [6]:
# multplication ( pointwise )
A * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]])>

In [7]:
# subtraction
A - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]])>

In [8]:
# tensorflow built in functions
tf.add(A, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]])>

In [9]:
tf.multiply(A, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]])>

In [10]:
tf.subtract(A, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]])>

## Matrix multiplication on tensors

In [11]:
matA = tf.constant([[1, 2], [3, 4]])
matB = tf.constant([[10, 20], [30, 40]])

tf.matmul(matA, matB)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 70, 100],
       [150, 220]])>

In [12]:
# matrix multiplication with python operator
matA * matB # this is element wise

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 10,  40],
       [ 90, 160]])>

In [14]:
matA @ matB # this is matrix multiplication using python operator directly

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 70, 100],
       [150, 220]])>

In [19]:
# inner dimensions must match for matrix multiplication
A = tf.ones(shape=(2,3))
B = tf.ones(shape=(2,3))

# tf.matmul(A,B)
tf.matmul(A, tf.transpose(B))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 3.],
       [3., 3.]], dtype=float32)>

In [21]:
tf.matmul(tf.transpose(A), B) # changing the shape of A instead of changing the shape of matrix B

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]], dtype=float32)>

In [22]:
tf.matmul(A, tf.reshape(B, shape=(3,2)))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 3.],
       [3., 3.]], dtype=float32)>

In [24]:
tf.matmul(tf.reshape(A, shape=(3,2)), B)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]], dtype=float32)>

## Dot Product ( tf.tensordot() )

In [26]:
matrixA = tf.constant([[1, 2], [3, 4], [5, 6]])
matrixB = tf.constant([[1, 2, 3], [4, 5, 6]])

# requires X or Y requires to be transposed

tf.tensordot(matrixA, matrixB, axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])>

In [27]:
# we get different result of matrix multiply if we use transpose or reshape
# Generally when performing matrix multiplication on tensor and one of the axes doesnt line up we will transpose the tensor rather than reshaping