In [1]:
import tensorflow as tf

## Aggregating Tensor

In [5]:
tensorA = tf.constant([1,2,3,4,5,6,7,8,9,0])
tensorA

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])>

In [7]:
tf.abs(tensorA) # absolute value of a corresponding in the input of a tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])>

In [11]:
# find the minimum of a tensor
tf.reduce_min(tensorA)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [13]:
# find the maximum
tf.reduce_max(tensorA).numpy()

9

In [14]:
# find the mean
tf.reduce_mean(tensorA).numpy()

4

In [15]:
# find the sum of a tensor
tf.reduce_sum(tensorA).numpy()

45

In [23]:
# variance need to access to tensorflow_probability
# tf.reduce_variance(tensorA).numpy()

In [27]:
tf.math.reduce_variance(tf.cast(tensorA, dtype=tf.float32)).numpy() # need to cast the tensor to dtype = tf.float32 input mus be real or comlex in order to calculate the variance

8.25

In [28]:
tf.math.reduce_std(tf.cast(tensorA, dtype=tf.float32)).numpy() # standard deviation

2.8722813

## Positional maximum and minimum

In [32]:
tf.random.set_seed(42)
new_tensor = tf.random.uniform(shape=(50,))
new_tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [36]:
max_indx = tf.argmax(new_tensor).numpy() # find the index of the maximum value in the tensor

In [37]:
new_tensor[max_indx].numpy() # find the maximum value in the tensor

0.9671384

In [39]:
min_indx = tf.argmin(new_tensor).numpy
min_indx

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int64, numpy=16>>

In [41]:
tf.reduce_max(new_tensor).numpy() == new_tensor[max_indx].numpy() # check if the maximum value is the same as the maximum value in the tensor

True

In [45]:
B = tf.random.uniform(shape=(3,3))
B

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.7413678 , 0.62854624, 0.01738465],
       [0.3431449 , 0.51063764, 0.3777541 ],
       [0.07321596, 0.02137029, 0.2871771 ]], dtype=float32)>

In [49]:
tf.argmax(B, axis=0).numpy() # find the index of the maximum value in each column whereas axis=1 for checking in rows of the matrix

array([0, 0, 1], dtype=int64)

## Squeeze the tensor

In [52]:
tf.random.set_seed(42)
sq_tensor = tf.constant(tf.random.uniform(shape=[50]), shape = (1,1,1,1,50))
sq_tensor

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [53]:
sq_tensor.shape

TensorShape([1, 1, 1, 1, 50])

In [55]:
sq_squeezed = tf.squeeze(sq_tensor) # remove the dimensions of size 1 from the shape of the tensor
sq_squeezed.shape

TensorShape([50])

## One-Hot-Encodings

In [56]:
some_list = [0,1,2,3] # This could be anything that we want to encode

# one hot encode the list of indices

tf.one_hot(some_list, depth=4) # depth is the number of classes in the list

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [58]:
# specify the custom values for the on and off values
tf.one_hot(some_list, depth=4, on_value="W", off_value="X")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'W', b'X', b'X', b'X'],
       [b'X', b'W', b'X', b'X'],
       [b'X', b'X', b'W', b'X'],
       [b'X', b'X', b'X', b'W']], dtype=object)>

## More math operations

In [59]:
tf.square(tensorA) # square the values of the tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81,  0])>

In [60]:
tf.range(1,10,2) # create a tensor with values from 1 to 10 with a step of 2

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [62]:
tf.sqrt(tf.cast(tensorA, dtype=tf.float32)) # square root of the tensor ( for the square root the input must be real or complex and data type must be float32 )

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       , 0.       ], dtype=float32)>

In [63]:
tf.math.log(tf.cast(tensorA, dtype=tf.float32)) # natural logarithm of the tensor

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246,      -inf], dtype=float32)>

In [64]:
tf.math.exp(tf.cast(tensorA, dtype=tf.float32)) # exponential of the tensor

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([2.7182817e+00, 7.3890562e+00, 2.0085537e+01, 5.4598148e+01,
       1.4841316e+02, 4.0342877e+02, 1.0966332e+03, 2.9809580e+03,
       8.1030840e+03, 1.0000000e+00], dtype=float32)>

## Tensors and Numpy

In [67]:
import numpy as np
numpy_tensor = tf.constant(np.array([1,2,3,4,5,6,7,8,9,0]))
numpy_tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])>

### Data type of tensor and numpy array are different keep in mind that

In [68]:
# convert tensor back to a numpy
np.array(numpy_tensor), type(np.array(numpy_tensor))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0]), numpy.ndarray)

In [69]:
# convert tensor to a numpy array
numpy_tensor.numpy(), type(numpy_tensor.numpy())

(array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0]), numpy.ndarray)