# Creating Tensors with tf.Variable

In [1]:
import tensorflow as tf

In [2]:
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [3]:
# changing one of the elements in changable tensor
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [4]:
# changing unchangable tensor
# unchangable_tensor[0].assign(7)
unchangable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

## Creating Random Tensors

### Random tensors are tensors of some arbitrary size which contains random numbers

In [5]:
# create two random tensors but same
random1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random1 = random1.normal(shape=(3,2)) # uniform distribution
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

##### tf normal outputs random value from a normal distribution

In [6]:
random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape=(3,2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [7]:
random1 == random2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffling the order of random tensors

In [8]:
# shuffle a tensor ( valuable when we want to shuffle our data so the inherent data wont affect the model)

not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
not_shuffled.ndim

2

In [9]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]])>

In [10]:
tf.random.shuffle(not_shuffled, seed = 42) # global and operation level seed might affect the shuffling

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

In [11]:
tf.random.set_seed(42) # global level seed and will generate the same random number
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

## Creating tensors from numpy

In [14]:
tf.ones([10,7], dtype=tf.int32)

<tf.Tensor: shape=(10, 7), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])>

In [15]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [16]:
# we can also turn numpy array into tensor
## The main difference between numpy array and tensor is that tensor can be run on GPU for faster computation

import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [18]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [20]:
B = tf.constant(numpy_A, shape=(6,4))
B

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])>

In [21]:
C = tf.constant(numpy_A, shape=(2,3,4))
C

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

### Getting information from tensors
* shape -> length of each of dimensions of a tensor
* rank -> number of tensors dimensions
* axis or dimension -> particular dimensions of a tensor
* size -> total number of items in a tensor

In [23]:
C.ndim, B.ndim, A.ndim

(3, 2, 1)

In [25]:
A.shape, B.shape, C.shape

(TensorShape([24]), TensorShape([6, 4]), TensorShape([2, 3, 4]))

In [28]:
rank_4_tensor = tf.zeros(shape=(2,3,4,5))

In [43]:
rank_4_tensor[0,0,0:2]

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [44]:
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor))
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy()) # to get the value

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor:  120
