#### Numpy

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [4]:
arr1[0:4]

array([1, 2, 3, 4])

In [5]:
arrr = np.array([[1,2,3], [4,5,6]])
arrr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arrr[0,0]

np.int64(1)

In [7]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.random.randint(0,100,(5,5))

array([[31, 20, 83, 71, 97],
       [11, 81, 83, 41,  9],
       [86, 94,  6, 84, 56],
       [35, 13, 86, 86, 59],
       [44, 26, 64, 95,  2]], dtype=int32)

In [9]:
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [11]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [12]:
B = A

In [14]:
B[0,0] = 0

In [15]:

A, B

(array([[0, 2],
        [3, 4]]),
 array([[0, 2],
        [3, 4]]))

In [16]:
A == B, A is B

(array([[ True,  True],
        [ True,  True]]),
 True)

In [17]:
A @ B

array([[ 6,  8],
       [12, 22]])

In [19]:
np.linalg.det(A).item()

-6.0

#### Pandas

In [20]:
import pandas as pd

In [21]:
s = pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [22]:
s.shape

(5,)

In [23]:
s.value_counts()

10    1
20    1
30    1
40    1
50    1
Name: count, dtype: int64

In [24]:
data = {"a": 1, "b": 2}
series_dict = pd.Series(data)
series_dict

a    1
b    2
dtype: int64

In [25]:
data = {
  "a": [1,2,3,4,5],
  "b": [11,22,33,44,55],
  "c": [111,222,333,444,555]
}

df = pd.DataFrame(data)
df

a   b    c
0  1  11  111
1  2  22  222
2  3  33  333
3  4  44  444
4  5  55  555

In [26]:
df["a"]

0    1
1    2
2    3
3    4
4    5
Name: a, dtype: int64

In [27]:
df[["a", "b"]]

a   b
0  1  11
1  2  22
2  3  33
3  4  44
4  5  55

In [28]:
df["a"][0:3]

0    1
1    2
2    3
Name: a, dtype: int64

In [31]:
pd.DataFrame(
  [[1,2,3],[3,4,5],[5,6,7]],
  columns=["a", "b", "c"]
)

a  b  c
0  1  2  3
1  3  4  5
2  5  6  7

In [32]:
df.shape

(5, 3)

In [33]:
df.columns

Index(['a', 'b', 'c'], dtype='object')

In [34]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [36]:
df.describe()

a          b          c
count  5.000000   5.000000    5.00000
mean   3.000000  33.000000  333.00000
std    1.581139  17.392527  175.50641
min    1.000000  11.000000  111.00000
25%    2.000000  22.000000  222.00000
50%    3.000000  33.000000  333.00000
75%    4.000000  44.000000  444.00000
max    5.000000  55.000000  555.00000

In [37]:
df.iloc[0]

a      1
b     11
c    111
Name: 0, dtype: int64

In [39]:
df.loc[0]

a      1
b     11
c    111
Name: 0, dtype: int64

In [40]:
df.loc[0:2]

a   b    c
0  1  11  111
1  2  22  222
2  3  33  333

In [41]:
df.loc[0:1, ["a"]]

a
0  1
1  2

In [47]:
left = pd.DataFrame({"ID": [1,2,3], "Name": ["A", "B", "C"]})
right = pd.DataFrame({"ID": [1,2,3], "Score": [80,90,100]})

In [44]:
pd.merge(left, right, on="ID", how="inner")

ID Name  Score
0   1    A     80
1   2    B     90
2   3    C    100

In [45]:
pd.concat([left, right], axis=0)

ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   80.0
1   2  NaN   90.0
2   3  NaN  100.0