## Pytorch Fundamentals:

In [4]:
print("Hello")

Hello


In [8]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


## Tensors
Creating tensors

Pytorch tensors are created using `torch.tensor`

In [10]:
## scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [12]:
scalar.ndim # dimension of scalar is 0

0

In [13]:
scalar.item() # get tensor back as int

7

In [14]:
## Vector
vector = torch.tensor([9,9])
vector

tensor([9, 9])

In [17]:
vector.ndim # dimension of vector

1

In [18]:
vector.shape

torch.Size([2])

In [19]:
## Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [20]:
MATRIX.shape, MATRIX.ndim

(torch.Size([2, 2]), 2)

In [21]:
MATRIX[0]

tensor([7, 8])

In [22]:
## Tensor
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [23]:
TENSOR.ndim

3

In [24]:
TENSOR.shape

torch.Size([1, 3, 3])

In [25]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

## Random Tensor
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [26]:
## Creating a random tensor of defined shape and size

random_tensor = torch.rand(3,3)
random_tensor

tensor([[0.7400, 0.4320, 0.4652],
        [0.1069, 0.4244, 0.5386],
        [0.4688, 0.4096, 0.4188]])

In [27]:
random_tensor = torch.rand(7,9)
random_tensor

tensor([[0.3756, 0.8460, 0.4597, 0.3525, 0.7313, 0.9886, 0.7526, 0.6178, 0.1363],
        [0.5752, 0.7439, 0.7749, 0.4588, 0.1691, 0.3692, 0.2121, 0.3319, 0.9402],
        [0.0893, 0.5178, 0.0662, 0.0787, 0.6563, 0.7836, 0.8554, 0.7765, 0.8190],
        [0.2072, 0.4442, 0.9306, 0.2126, 0.7701, 0.4763, 0.4218, 0.4676, 0.0810],
        [0.1469, 0.5647, 0.8970, 0.7496, 0.3238, 0.3773, 0.6724, 0.9260, 0.0768],
        [0.3608, 0.8254, 0.4800, 0.9164, 0.6337, 0.1186, 0.4586, 0.6531, 0.9633],
        [0.2148, 0.5256, 0.7093, 0.1598, 0.5960, 0.8254, 0.4493, 0.0715, 0.5102]])

In [28]:
random_tensor = torch.rand(3,3,3)
random_tensor

tensor([[[0.1637, 0.3971, 0.1091],
         [0.4017, 0.4358, 0.6353],
         [0.1595, 0.4347, 0.3873]],

        [[0.0965, 0.4614, 0.7895],
         [0.8920, 0.3493, 0.5809],
         [0.5650, 0.4348, 0.8413]],

        [[0.6552, 0.0363, 0.8119],
         [0.0379, 0.3477, 0.0477],
         [0.4861, 0.7226, 0.5391]]])

In [29]:
random_tensor.ndim, random_tensor.shape

(3, torch.Size([3, 3, 3]))

In [32]:
## Create a random tensor with shape to an image
## Image with h and w of 224 and 3 channel for rgb

image_size_random_tensor = torch.rand(size=(3,224,224))
image_size_random_tensor.shape, image_size_random_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and Ones Tensors


In [33]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [35]:
ones.dtype # datatype of tensor

torch.float32

## Range of Tensors and Tensors-like

In [36]:
range = torch.range(0,10) # depricated use arange
range

<ipython-input-36-91a60021e470>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range = torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
range = torch.arange(0,10)
range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
range = torch.arange(start=0, end=1000, step=77) # start , end and step argument
range

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [42]:
tensor_like = torch.zeros_like(range) # create zeros tensors like the tensor range above
tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
tensor_like = torch.ones_like(range) # create ones tensors like the tensor range above
tensor_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Tensor datatypes
- 32-bit floating point
- 16-bit floating point
...
for precision

In [44]:
float_32_tensor = torch.tensor([1.0, 2.0],
                               dtype=None,) # by default the data type if float 32
float_32_tensor.dtype

torch.float32

Tensor datatypes is one of the three big errors we will run into.

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [50]:
tensor = torch.tensor([1.0, 2.0],
                      dtype=torch.float16, # what datatype of tensor
                      device=None, # what device is our tensor
                      requires_grad=False) # whether or not to track gradient
tensor.dtype

torch.float16

In [51]:
## Changing the datatype of the tensor

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2.], dtype=torch.float16)

In [52]:
multiplied_tensor = float_16_tensor * float_32_tensor
multiplied_tensor

tensor([1., 4.])

In [54]:
multiplied_tensor.dtype

torch.float32

In [55]:
int_32_tensor = torch.tensor([1,2], dtype=torch.int32)
int_32_tensor

tensor([1, 2], dtype=torch.int32)

In [57]:
multiplied_tensor = int_32_tensor * float_32_tensor
multiplied_tensor, multiplied_tensor.dtype

(tensor([1., 4.]), torch.float32)

## Getting information from tensors:

1. Tensors not right datatype `tensor.dtype`
2. Tensors not right shape `tensor.shape`
3. Tensor not on the right device `tensor.device`

We can debug by the use of these information and convert into the required type

- `torch_tensor.type(torch.float32)`

In [59]:
tensor = torch.rand(size=(3,3))

print(f"Datatype of tensor: {tensor.dtype}")
print(f"Shape of tensor: {tensor.shape}")
print(f"Device of tensor: {tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 3])
Device of tensor: cpu
