## Tensor manipulation

1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix multiplication

In [1]:
import torch

In [6]:
tensor_a = torch.rand(size=(3,3))
tensor_b = torch.rand(size=(3,3))

# Addition of tensor
tensor_c = torch.add(tensor_a, tensor_b)
tensor_c

tensor([[1.9591, 1.1277, 0.8025],
        [0.5930, 0.8714, 1.5237],
        [1.6000, 0.5669, 0.3782]])

In [4]:
tensor_a = tensor_a + 10 # Element wise addition of scalar
tensor_a

tensor([[10.2255, 10.3323, 10.9067],
        [10.4743, 10.7091, 10.6461],
        [10.1266, 10.9149, 10.9829]])

In [5]:
# multiply tensor
tensor_a = torch.ones(size=(3,3))
tensor_a * 10

tensor([[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]])

In [7]:
# divide tensor
tensor_a = torch.ones(size=(3,3))
tensor_a / 10

tensor([[0.1000, 0.1000, 0.1000],
        [0.1000, 0.1000, 0.1000],
        [0.1000, 0.1000, 0.1000]])

In [8]:
## inbuilt function
torch.mul(tensor_a, 10)

tensor([[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]])

In [9]:
torch.add(tensor_a, 10)

tensor([[11., 11., 11.],
        [11., 11., 11.],
        [11., 11., 11.]])

In [10]:
torch.sub(tensor_a, 10)

tensor([[-9., -9., -9.],
        [-9., -9., -9.],
        [-9., -9., -9.]])

In [12]:
## matrix multiplication
## 1. Element wise multiplication
## 2. matrix multiplication

element_wise_mul = tensor_a * 10
matrix_mul = torch.matmul(tensor_a, tensor_b)

print(element_wise_mul)
print(matrix_mul)

tensor([[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]])
tensor([[1.9387, 1.4583, 1.2030],
        [1.9387, 1.4583, 1.2030],
        [1.9387, 1.4583, 1.2030]])


In [22]:
a = torch.rand(size=(1,2))
b = torch.rand(size=(2,1))

## Inner dimension of matrix must match for matrix multiplication
c = torch.matmul(a,b)
c, c.shape

(tensor([[0.5892]]), torch.Size([1, 1]))

In [16]:
c.item() # getting scalar value from tensor

0.3655586242675781

In [18]:
tensor = torch.tensor([1,2,3])

In [20]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(f"Multiplication: {value}")

Multiplication: 14
CPU times: user 3.17 ms, sys: 0 ns, total: 3.17 ms
Wall time: 3.67 ms


In [21]:
%%time
value = torch.matmul(tensor, tensor)
print(f"Multiplication: {value}")

Multiplication: 14
CPU times: user 2.62 ms, sys: 30 µs, total: 2.65 ms
Wall time: 2.33 ms


In [26]:
tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_b = torch.tensor([[7,10],
                        [8,12],
                        [9,20]])

tensor_a.shape == tensor_b.shape

True

In [27]:
## Transpose of matrix

tensor_a.shape, tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [28]:
tensor_b_transponse = tensor_b.T
tensor_b_transponse

tensor([[ 7,  8,  9],
        [10, 12, 20]])

In [29]:
torch.mm(tensor_a, tensor_b_transponse)

tensor([[ 27,  32,  49],
        [ 61,  72, 107],
        [ 95, 112, 165]])

In [30]:
torch.matmul(tensor_a.T, tensor_b)

tensor([[ 76, 146],
        [100, 188]])