## Tensor Aggregation
- min
- max
- mean
- sum

In [1]:
import torch

In [2]:
tensor_a = torch.arange(0,100,20)
tensor_a

tensor([ 0, 20, 40, 60, 80])

In [4]:
min = torch.min(tensor_a)
max = torch.max(tensor_a)
sum = torch.sum(tensor_a)
# mean = torch.mean(tensor_a.type(torch.float32))
print(min,max,sum)

tensor(0) tensor(80) tensor(200)


In [6]:
tensor_a.dtype

torch.int64

In [7]:
mean = torch.mean(tensor_a.type(torch.float32)) # because int64 dtype is long for the mean aggreagation function
mean

tensor(40.)

In [9]:
## Finding the positional min and max

tensor = torch.arange(10,20,2)
tensor.argmin(), tensor.argmax(), tensor # get the index position of max and min

(tensor(0), tensor(4), tensor([10, 12, 14, 16, 18]))

## Reshaping, viewing and stacking tensor

1. Reshaping : reshape the input tensor to a defined shape
2. View : Return view of an input tensor of certain shape but keep the same memory as original
3. Stacking : Combine multiple tensors on top of each tensor (v-stack) or (h-stack)
4. Squeeze: removes all 1 dimensions from a tensor
5. Unsqueeze : add a 1 dimension to a target tensor
6. Permute : Return a view of the input with dimensions permuted (swapped) in certain way

In [10]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [12]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [15]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [20]:
x = torch.ones(size=(1,9))
x

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
x.reshape(9,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [22]:
## Changing the view

x = torch.arange(1., 10.)
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [23]:
## they share same memory
x[0] = 99
z

tensor([[99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [25]:
## Stacking

x_stacked = torch.stack([x,x,x,x], dim=0) # dim 0 means x in dim0
x_stacked

tensor([[99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [26]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[99., 99., 99., 99.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.]])

In [27]:
## Squeeze

x = torch.zeros(size=(224,224,3))
x.shape

torch.Size([224, 224, 3])

In [28]:
y = torch.squeeze(x)
y.shape

torch.Size([224, 224, 3])

In [34]:
x = torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
x.reshape(shape=(1,9))
x, x.ndim

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), 1)

In [36]:
x.squeeze()

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
x = torch.tensor([[1,2,3,4,5,6,7,8,9,0]])
x.shape

torch.Size([1, 10])

In [38]:
x.squeeze()

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [39]:
## Unsqueeze

x = torch.arange(1,10)
x.shape

torch.Size([9])

In [45]:
x = x.unsqueeze(dim=0)
x

tensor([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [46]:
x = x.squeeze()
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
## permute: rearrange the dimension of the tensor

x = torch.rand(size=(224,224,3))

# changing the dimension so that color channel come at the first
x_permuted = x.permute(2, 0, 1) # 2nd index at 0th , 0th index at second and 1st index at 2nd position
x_permuted.shape

torch.Size([3, 224, 224])

In [55]:
a = torch.rand(size=(9,9,3))
a_permuted = a.permute(2,0,1)
a_permuted, a

(tensor([[[5.4849e-01, 1.5847e-01, 7.9589e-01, 5.3965e-01, 4.5066e-01,
           8.1473e-02, 8.6614e-01, 1.1258e-01, 4.3921e-01],
          [1.4841e-01, 8.2055e-01, 3.1714e-01, 4.8396e-01, 3.7235e-01,
           3.9101e-05, 3.0154e-02, 1.9709e-01, 7.2235e-01],
          [5.2109e-02, 4.1823e-02, 3.0250e-01, 2.0230e-02, 3.6656e-01,
           3.1677e-01, 8.9898e-01, 9.0595e-01, 3.9938e-01],
          [8.7989e-01, 6.3608e-01, 5.6047e-01, 8.5287e-01, 1.0758e-01,
           9.7192e-01, 4.1873e-01, 4.2033e-01, 6.7788e-01],
          [5.2570e-01, 7.7703e-01, 4.6811e-01, 2.3421e-01, 2.0980e-01,
           7.4250e-01, 5.0055e-01, 3.4524e-01, 1.0432e-01],
          [2.2117e-01, 3.8362e-02, 3.9377e-01, 5.9318e-01, 6.6547e-01,
           8.6116e-01, 7.8901e-01, 6.6064e-01, 4.0169e-01],
          [2.9481e-01, 3.9135e-01, 6.7731e-01, 7.2076e-01, 9.3037e-01,
           4.1377e-02, 2.5891e-01, 8.2469e-01, 9.4159e-01],
          [6.0557e-01, 8.1045e-01, 3.5070e-01, 2.1797e-01, 4.7597e-01,
           9

## Indexing

In [56]:
a = torch.arange(1,10).reshape(1,3,3)
a

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [60]:
a[0], a[0][1], a[0][1][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([4, 5, 6]),
 tensor(4))

In [61]:
z = torch.arange(1,10).reshape(1,3,3)
z

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [64]:
z[0, 0:2, 0:2] # first matrix and then slice the matrix

tensor([[1, 2],
        [4, 5]])

In [66]:
tensor_a = torch.rand(size=(7,7))
tensor_a, tensor_a.shape

(tensor([[0.6707, 0.1852, 0.9314, 0.4457, 0.5870, 0.2546, 0.3818],
         [0.8192, 0.2262, 0.3544, 0.6172, 0.5871, 0.4127, 0.4433],
         [0.0994, 0.5899, 0.9976, 0.3170, 0.9503, 0.5829, 0.9841],
         [0.7683, 0.9287, 0.7588, 0.9764, 0.4492, 0.7999, 0.8525],
         [0.7228, 0.6872, 0.6879, 0.3903, 0.3458, 0.5752, 0.2192],
         [0.6201, 0.6524, 0.5748, 0.0745, 0.3861, 0.6723, 0.4430],
         [0.3933, 0.5086, 0.9767, 0.6849, 0.7841, 0.2158, 0.5369]]),
 torch.Size([7, 7]))

In [74]:
tensor_a[::2, ::] # all element from row, column with stride of 2 and null

tensor([[0.6707, 0.1852, 0.9314, 0.4457, 0.5870, 0.2546, 0.3818],
        [0.0994, 0.5899, 0.9976, 0.3170, 0.9503, 0.5829, 0.9841],
        [0.7228, 0.6872, 0.6879, 0.3903, 0.3458, 0.5752, 0.2192],
        [0.3933, 0.5086, 0.9767, 0.6849, 0.7841, 0.2158, 0.5369]])