## Pytorch tensors and numpy

In [1]:
import torch
import numpy as np

In [2]:
array = np.arange(1, 10, 1)
tensor = torch.from_numpy(array)

tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
tensor.dtype # because default dtype of numpy

torch.int64

In [5]:
tenosr_float_32 =tensor.type(torch.float32)
tenosr_float_32.dtype

torch.float32

In [7]:
## to numpy convert

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
numpy_tensor, numpy_tensor.dtype # default of pytorch float32

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32), dtype('float32'))

## Random out of Random
To reduce the randomness, the concept of random seed is used. There is not true actual randomness, computer is fundamentally deterministic so we can acutally control the random generation.

Here we can do by seeding.

In [9]:
torch.rand(3,3) # every time random

tensor([[0.3954, 0.9510, 0.8863],
        [0.3904, 0.6585, 0.4528],
        [0.7644, 0.5164, 0.1296]])

In [13]:
tensor_a = torch.rand(3,3)
tensor_b = torch.rand(3,3)

print(tensor_a)
print(tensor_b)
print(tensor_a == tensor_b)

tensor([[0.6221, 0.4943, 0.0606],
        [0.4257, 0.0725, 0.4112],
        [0.6773, 0.4117, 0.5328]])
tensor([[0.2928, 0.5701, 0.5578],
        [0.9234, 0.7462, 0.8301],
        [0.9635, 0.3773, 0.1775]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [15]:
## seeding: give random seed at first

RANDOM_SEED = 2
torch.manual_seed(RANDOM_SEED)

tensor_a = torch.rand(3,3)
tensor_b = torch.rand(3,3)

print(tensor_a)
print(tensor_b)
print(tensor_a == tensor_b)

tensor([[0.6147, 0.3810, 0.6371],
        [0.4745, 0.7136, 0.6190],
        [0.4425, 0.0958, 0.6142]])
tensor([[0.0573, 0.5657, 0.5332],
        [0.3901, 0.9088, 0.5334],
        [0.7073, 0.7116, 0.2050]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [18]:
## Only work the seed for the current cell

torch.manual_seed(2)
tensor_a = torch.rand(3,3)

torch.manual_seed(2)
tensor_b = torch.rand(3,3)

print(tensor_a)
print(tensor_b)
print(tensor_a == tensor_b)

tensor([[0.6147, 0.3810, 0.6371],
        [0.4745, 0.7136, 0.6190],
        [0.4425, 0.0958, 0.6142]])
tensor([[0.6147, 0.3810, 0.6371],
        [0.4745, 0.7136, 0.6190],
        [0.4425, 0.0958, 0.6142]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


## Running tenosrs and Pytorch object on the  GPU available and make faster computation.

## Device agnostic code.
Since pytorch is capable of running compute on GPU or CPU, it is best practice to setup device agnostic code.

In [19]:
## Check for GPU available or not

torch.cuda.is_available()

False

In [20]:
## Setup device agnostic code
## Use the GPU if available in the machine

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [23]:
## Count number of device

torch.cuda.device_count() # 0 if running on CPU

0

## Setting device agnostic code and putting tensors on and off the GPU.

In [24]:
# creating a tensor
tensor = torch.tensor([1,2,3])

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [26]:
# moving to the GPU if available

device = "cuda" if torch.cuda.is_available() else "cpu"

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [29]:
## We will get error if running on CPU and use cuda for the GPU

# tensor_gpu = torch.tensor([1,2,3], device = "cuda")
# tensor_gpu

# RuntimeError                              Traceback (most recent call last)
# <ipython-input-27-a213ad52e5cf> in <cell line: 1>()
# ----> 1 tensor_gpu = torch.tensor([1,2,3], device = "cuda")
#       2 tensor_gpu

# /usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py in _lazy_init()
#     312         if "CUDA_MODULE_LOADING" not in os.environ:
#     313             os.environ["CUDA_MODULE_LOADING"] = "LAZY"
# --> 314         torch._C._cuda_init()
#     315         # Some of the queued calls may reentrantly call _lazy_init();
#     316         # we need to just return without initializing in that case.

# RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [33]:
## Moving tensor back to CPU

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy() # fist convert to CPU and to numpy
tensor_back_on_cpu

array([1, 2, 3])