# Iterating

In [1]:
import numpy as np

In [3]:
a1 = np.arange(1,10)
a2 = np.arange(1, 10).reshape(3,3)
a3 = np.arange(27).reshape(3,3,3)

In [4]:
a1, a2, a3

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],
 
        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]]))

In [5]:
for i in a1:
    print(i)

1
2
3
4
5
6
7
8
9


In [7]:
print(a2)
for i in a2:
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[4 5 6]
[7 8 9]


In [8]:
print(a3)
print("\n")

for i in a3:
    print(i)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [9]:
for i in a3:
    for j in i:
        print(j)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]
[12 13 14]
[15 16 17]
[18 19 20]
[21 22 23]
[24 25 26]


In [12]:
b3 = np.arange(8).reshape(2,2,2)
b3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [14]:
for i in np.nditer(b3):
    print(i) # first convert to 1D then iterate

0
1
2
3
4
5
6
7


In [15]:
b2 = np.arange(4).reshape(2,2)
b2

array([[0, 1],
       [2, 3]])

In [17]:
b2_transpose = np.transpose(b2)
b2_transpose

array([[0, 2],
       [1, 3]])

In [19]:
# convert any dim arrays to 1Darray in np
np.ravel(b2)

array([0, 1, 2, 3])

In [21]:
# convert any dim arrays to 1Darray in np
np.ravel(b3)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [22]:
h1 = np.arange(5)
h2 = np.arange(6).reshape(2,3)

h1, h2

(array([0, 1, 2, 3, 4]),
 array([[0, 1, 2],
        [3, 4, 5]]))

In [25]:
# all the input arrays must have same number of dimensions
hstack2 = np.hstack((h2, h2))
hstack2

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [26]:
hstack1 = np.hstack((h1, h1))
hstack1

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [27]:
# Vertical stacking 1 dim array
vstack1 = np.vstack((h1, h1))
vstack1

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [28]:
# Vertical stacking 2 dim array
vstack2 = np.vstack((h2, h2))
vstack2

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [35]:
hsplit2 = np.hsplit(h2,3)
hsplit2, h2

([array([[0],
         [3]]),
  array([[1],
         [4]]),
  array([[2],
         [5]])],
 array([[0, 1, 2],
        [3, 4, 5]]))

In [39]:
hsplit1 = np.hsplit(h1,5) # equal maa split hunu paryo
h1, hsplit1

(array([0, 1, 2, 3, 4]),
 [array([0]), array([1]), array([2]), array([3]), array([4])])

In [40]:
hsplit01 = np.hsplit(np.arange(6), 2) # 2 taa equal parts maa split garne
hsplit01

[array([0, 1, 2]), array([3, 4, 5])]