# Indexing and Slicing

In [21]:
import numpy as np

a1 = np.arange(1,10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)

In [22]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [23]:
a1[-1]
# This returns the last element

9

In [10]:
a2[-1]
# In terms of 2 dimensional array this will return the last row from the matrix

array([ 8,  9, 10, 11])

In [11]:
a3[-1]
# In terms of 3 dimensional array this will return the last matrix from the array

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [24]:
a1[0], a2[0], a3[0]

(1,
 array([0, 1, 2, 3]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]))

In [14]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
a2[0][0], a2[0,3], a2[2,3]

(0, 3, 11)

In [16]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [18]:
a3[0][0][0], a3[0][2][1]

(0, 7)

In [19]:
a3[0][0], a3[2][1]

(array([0, 1, 2]), array([21, 22, 23]))

In [25]:
print(a1)
print("\n")
print(a1[2:5])

[1 2 3 4 5 6 7 8 9]


[3 4 5]


In [29]:
print(a2)
print("\n")
print("Print all the column of the first row")
print(a2[0,:])

print("Print the all rows of the first column")
print(a2[:, 0])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Print all the column of the first row
[0 1 2 3]
Print the all rows of the first column
[0 4 8]


In [30]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [31]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [41]:
a3[::2] # stride of 2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [38]:
a2, a2[:2]

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[0, 1, 2, 3],
        [4, 5, 6, 7]]))

In [40]:
a1, a1[2:5:2] # stride of 2

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([3, 5]))

In [46]:
a2, a2[1:], a2[1:, 2:], a2[1:, 2:3] # a2 ko 1 dekhi uta ra column ma 2 dekhi 3

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 6,  7],
        [10, 11]]),
 array([[ 6],
        [10]]))

In [48]:
a2, a2[::2,::3] # row ma 2 stride (1 xodne) ra column maa 3 stride vaneko (2 xodne)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  3],
        [ 8, 11]]))

In [50]:
a3, a3[0], a3[0, 0:2], a3[0, 0:2, 1:2]

(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],
 
        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[0, 1, 2],
        [3, 4, 5]]),
 array([[1],
        [4]]))

In [51]:
a3[0, 2,:]

array([6, 7, 8])