In [1]:
import numpy as np

# Create Array

In [2]:
# create array

a = np.array([])
b = np.array([[],[]])
a, b

(array([], dtype=float64), array([], shape=(2, 0), dtype=float64))

In [4]:
# numpy array with data type

data_type = np.array([], dtype=float) # default float64
data_type

array([], dtype=float64)

In [5]:
arange = np.arange(1,11)
arange

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arange_with_stride = np.arange(1,11,2) # skip 2
arange_with_stride

array([1, 3, 5, 7, 9])

In [9]:
arange_with_shape = np.arange(1,11).reshape(2,5) # rows 2 and column 5
# here the shape and number of elements should match
arange_with_shape

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
arange_with_shape.reshape(5,2) # rows 5 and column 2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [11]:
# array with ones and zeros
np_ones = np.ones((3,4))
np_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np_zeros = np.zeros((3,4))
np_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np_random = np.random.random((3,4)) # 0 to 1
np_random

array([[0.99014704, 0.36312576, 0.83028153, 0.52341642],
       [0.73471119, 0.49702075, 0.76599428, 0.06611367],
       [0.74981414, 0.60877438, 0.492205  , 0.71631803]])

In [18]:
linspace1 = np.linspace(1,10,5) # give 5 elements betweeen 1 and 10
linspace2 = np.linspace(10,-10,10) # give 10 elements between -10 and 10
linspace1, linspace2

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]),
 array([ 10.        ,   7.77777778,   5.55555556,   3.33333333,
          1.11111111,  -1.11111111,  -3.33333333,  -5.55555556,
         -7.77777778, -10.        ]))

# Array attributes

In [20]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3, 4)
a3 = np.arange(8).reshape(2,2,2)

a1, a2, a3

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

In [23]:
print(a1.ndim, a2.ndim, a3.ndim)
# dimensions of array a1, a2 ,a3

1 2 3


In [24]:
print(a1.shape, a2.shape, a3.shape)
# shape of array

(10,) (3, 4) (2, 2, 2)


In [25]:
print(a1.size, a2.size, a3.size)
# size of array (total number of elements)

10 12 8


In [29]:
print(a1.dtype, a2.dtype, a3.dtype)
# data type of array

int32 float64 int32


In [30]:
a3.astype(np.float32)
# changing the datatype

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]], dtype=float32)

# Array Operations

In [31]:
a2 = np.arange(10).reshape(2,5)
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
a2 = a2 * 5 # scaler operation arithmetic
a2

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

In [33]:
bool_a2 = a2 > 20
# returns boolean matrix True False
bool_a2

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True]])

In [36]:
mat_a = np.ones((3,2))
mat_b = np.ones((3,2))

mat_c = mat_a + mat_b # addition
mat_d = mat_a * mat_b  # multiplication (pointwise)

mat_c , mat_d

(array([[2., 2.],
        [2., 2.],
        [2., 2.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]))

# Array Functions

In [38]:
a1 = np.random.random((3,3))
a1

array([[0.63716468, 0.61826568, 0.29841931],
       [0.97039999, 0.83984535, 0.54868274],
       [0.11612388, 0.82349475, 0.59290612]])

In [40]:
a1 = np.round(a1 * 100)
a1, a1.dtype

(array([[6400., 6200., 3000.],
        [9700., 8400., 5500.],
        [1200., 8200., 5900.]]),
 dtype('float64'))

In [42]:
max = np.max(a1)
sum = np.sum(a1)
min = np.min(a1)
prod = np.prod(a1)

print("MAX:", max)
print("SUM", sum)
print("MIN", min)
print("PROD:", prod)

MAX: 9700.0
SUM 54500.0
MIN 1200.0
PROD: 3.0970893735936e+33


In [48]:
a2 = np.linspace(1,6,6)
print(a2)

print(np.prod(a2))

[1. 2. 3. 4. 5. 6.]
720.0


In [54]:
a2 = np.linspace(1,100,25).reshape(5,5)
a2, a2.max()

(array([[  1.   ,   5.125,   9.25 ,  13.375,  17.5  ],
        [ 21.625,  25.75 ,  29.875,  34.   ,  38.125],
        [ 42.25 ,  46.375,  50.5  ,  54.625,  58.75 ],
        [ 62.875,  67.   ,  71.125,  75.25 ,  79.375],
        [ 83.5  ,  87.625,  91.75 ,  95.875, 100.   ]]),
 100.0)

In [52]:
np.max(a2, axis=1)
# find the max of each row

array([ 17.5  ,  38.125,  58.75 ,  79.375, 100.   ])

In [53]:
# find the max of each column
np.max(a2, axis=0)

array([ 83.5  ,  87.625,  91.75 ,  95.875, 100.   ])

In [55]:
np.mean(a2), np.median(a2), np.std(a2), np.var(a2), np.sin(a2), np.cos(a2)

(50.5,
 50.5,
 29.74579802257791,
 884.8125,
 array([[ 0.84147098, -0.91607692,  0.17388949,  0.72334146, -0.97562601],
        [ 0.35802197,  0.57880195, -0.99955393,  0.52908269,  0.41312976],
        [-0.98698706,  0.68082602,  0.23237376, -0.93838423,  0.80771166],
        [ 0.04313354, -0.85551998,  0.90510688, -0.14768153, -0.74141977],
        [ 0.96945567, -0.33310459, -0.60024952,  0.99840858, -0.50636564]]),
 array([[ 0.54030231,  0.40100259, -0.98476517,  0.6904905 ,  0.21943996],
        [-0.93371316,  0.81546815,  0.02986535, -0.84857027,  0.91067217],
        [-0.16079968, -0.73244517,  0.97262656, -0.34559374, -0.5895777 ],
        [ 0.99906932, -0.5177698 , -0.42518412,  0.98903497, -0.67104152],
        [-0.2452666 ,  0.94288988, -0.7998128 , -0.05639413,  0.86231887]]))

In [63]:
# Dot product

mat_a = np.arange(1,13).reshape(4,3)
mat_b = np.arange(12).reshape(3,4)

if (mat_a.shape[1] == mat_b.shape[0]):
    print("Dot product possible")
    mat_c = np.dot(mat_a, mat_b)
    print(mat_c)
else:
    print("Dot product not possible")
    print("Shape of mat_a", mat_a.shape)
    print("Shape of mat_b", mat_b.shape)

Dot product possible
[[ 32  38  44  50]
 [ 68  83  98 113]
 [104 128 152 176]
 [140 173 206 239]]


In [64]:
zeros = np.zeros((3,3))
print(np.exp(zeros)) # exponential of the matrix

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [70]:
np.round(np.random.random((2,1)) * 100)

array([[20.],
       [73.]])

In [77]:
random = np.random.random((3,3))
random

array([[0.41767468, 0.01363896, 0.94877726],
       [0.4292762 , 0.29690912, 0.18942634],
       [0.27966497, 0.51676848, 0.12088691]])

In [78]:
np.floor(random), np.ceil(random)

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [79]:
array = np.array([1.2,1.1,1.9,9.9,0.01,0.09,0.9], dtype=np.float16)
array

array([1.2 , 1.1 , 1.9 , 9.9 , 0.01, 0.09, 0.9 ], dtype=float16)

In [81]:
np.ceil(array), np.floor(array)

(array([ 2.,  2.,  2., 10.,  1.,  1.,  1.], dtype=float16),
 array([1., 1., 1., 9., 0., 0., 0.], dtype=float16))

In [82]:
list = [1 ,2, 3, 4, 5]
type(list)

list

In [84]:
np_array = np.asarray(list)
type(np_array), np_array

(numpy.ndarray, array([1, 2, 3, 4, 5]))

In [85]:
np_array = np.array(list)
type(np_array), np_array

(numpy.ndarray, array([1, 2, 3, 4, 5]))